---
name: "Build Container"
description: "Builds a container from a Dockerfile using minimal input."

inputs:
  app_name:
    required: true
  version:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Build and push ${{ inputs.app_name }} container
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./apps/${{ inputs.app_name }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
