name: Release NZBGet

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/nzbget.yml
      - apps/nzbget/**

jobs:
  release:
    name:
    runs-on: ubuntu-20.04
    env:
      APP_NAME: nzbget
      VERSION: 21.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ env.APP_NAME }} container
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./apps/${{ env.APP_NAME }}
          tags: ghcr.io/${{ github.actor }}/${{ env.APP_NAME }}:${{ env.VERSION }}
          build-args: |
            TARGET_PLATFORM=x86_64
            VERSION=${{ env.VERSION }}
