name: Release pgloader

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/pgloader.yml
      - apps/pgloader/**

jobs:
  release:
    name:
    runs-on: ubuntu-22.04
    env:
      APP_NAME: pgloader
      VERSION: pr-1531
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build Container
        uses: ./.github/actions/build_container
        with:
          app_name: ${{ env.APP_NAME }}
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
